Adding transactions
usernein/api-treino pull request #3
Opened 2021-04-06 21:13 UTC by usernein

2021-04-06 21:22 UTC, Tisp requested changes

2021-04-06 21:22 UTC, Tisp commented on src/Storage.php
>          return true;
Aqui seria melhora você validar se o returno do file put contents ocorreu corretamente .  Retornar apenas null induz ao erro

2021-04-06 21:22 UTC, Tisp commented on src/Transaction.php
> +        }
Aqui você pode capturar multiplos exceptions e chamar uma unica vez o `getUserById`

2021-04-06 22:43 UTC, jp-ataide commented on src/Transaction.php
> +        }
Por qual motivo foi adicionado uma transformation de exceptions ?

2021-04-06 22:43 UTC, jp-ataide commented on src/User.php
>          if (!isset($userFields['name']) || !isset($userFields['document']) || !isset($userFields['type'])) {
o que aconteceria se eu informasse nesse campo: name = null ?

2021-04-07 13:31 UTC, usernein commented on src/Transaction.php
> +        }
Para identificar se o usuário não existente é o payer ou receiver

2021-04-07 13:34 UTC, usernein commented on src/User.php
>          if (!isset($userFields['name']) || !isset($userFields['document']) || !isset($userFields['type'])) {
O isset retornaria falso e uma exceção UserAPINotEnoughData seria lançada

2021-04-07 13:35 UTC, usernein commented on src/Transaction.php
> +        }
@Tisp mesmo sendo para pegar dois usuários diferentes?

2021-04-07 13:36 UTC, usernein commented on src/Storage.php
>          return true;
Apenas retornar o valor do file_put_contents?

2021-04-07 13:47 UTC, jp-ataide commented on src/User.php
>          if (!isset($userFields['name']) || !isset($userFields['document']) || !isset($userFields['type'])) {
e se eu trocar o name pra 0 ?

2021-04-07 13:58 UTC, usernein commented on src/User.php
>          if (!isset($userFields['name']) || !isset($userFields['document']) || !isset($userFields['type'])) {
Aí precisa de validação mais forte mesmo :v

2021-04-07 19:38 UTC, usernein commented on src/User.php
>          if (!isset($userFields['name']) || !isset($userFields['document']) || !isset($userFields['type'])) {
@jp-ataide vi aqui que já tem validação para caso a chave exista mas com valor inválido: https://github.com/usernein/api-treino/blob/89b6f366f55396c9bd10f6483667b875f9dddb18/src/User.php#L33

2021-04-09 17:13 UTC, Tisp commented on src/Storage.php
>          return true;
Quis dizer que voce deve validar se o `file_put_contents` ocorreu corretamente

2021-04-09 17:14 UTC, Tisp commented on src/Transaction.php
> +        }
Sim

2021-04-14 13:17 UTC, usernein commented on src/Storage.php
>          return true;
Feito no e3e1afc

2021-04-14 13:17 UTC, merged